# agreety
# Autogenerated from man page /usr/share/man/man1/agreety.1.gz
complete -c agreety -s c -l cmd -d 'Specifies the command to run on successful login'
complete -c agreety -s f -l max-failures -d 'Specifies the maximum number of login failures to accept before terminating'

