# apxs
# Autogenerated from man page /usr/share/man/man1/apxs.1.gz
complete -c apxs -s n -d 'This explicitly sets the module name for the -i (install) and -g (template ge…'
complete -c apxs -s q -d 'Performs a query for variables and environment settings used to build httpd'
complete -c apxs -s S -d 'This option changes the apxs settings described above'
complete -c apxs -s g -d 'This generates a subdirectory name (see option -n) and there two files: A sam…'
complete -c apxs -s c -d 'This indicates the compilation operation'
complete -c apxs -s o -d 'Explicitly specifies the filename of the created dynamically shared object'
complete -c apxs -s D -d 'This option is directly passed through to the compilation command(s)'
complete -c apxs -s I -d 'This option is directly passed through to the compilation command(s)'
complete -c apxs -s L -d 'This option is directly passed through to the linker command'
complete -c apxs -s l -d 'This option is directly passed through to the linker command'
complete -c apxs -o Wc -d 'This option passes compiler-flags as additional flags to the libtool --mode=c…'
complete -c apxs -o Wl -d 'This option passes linker-flags as additional flags to the libtool --mode=lin…'
complete -c apxs -s p -d 'This option causes apxs to link against the apr/apr-util libraries'
complete -c apxs -s i -d 'This indicates the installation operation and installs one or more dynamicall…'
complete -c apxs -s a -d 'This activates the module by automatically adding a corresponding LoadModule …'
complete -c apxs -s A -d 'Same as option -a but the created LoadModule directive is prefixed with a has…'

