# avifdec
# Autogenerated from man page /usr/share/man/man1/avifdec.1.gz
complete -c avifdec -s h -l help -d 'Show syntax help'
complete -c avifdec -s V -l version -d 'Show the version number'
complete -c avifdec -s j -l jobs -d 'Number of jobs (worker threads).  1 or less means single-threaded'
complete -c avifdec -s c -l codec -d 'AV1 codec to use'
complete -c avifdec -s d -l depth -d 'Output PNG depth'
complete -c avifdec -s q -l quality -d 'Output JPEG quality in the range 0-100.  Default is 90'
complete -c avifdec -l png-compress -d 'Output PNG compression level in the range 0-9 (fastest to maximum compression)'
complete -c avifdec -s u -l upsampling -d 'Chroma upsampling method.  Ignored unless the input format is 4:2:0 or 4:2:2'
complete -c avifdec -s r -l raw-color -d 'Output raw RGB values instead of multiplying by alpha when saving to opaque f…'
complete -c avifdec -l index -d 'When decoding an image sequence or progressive image, specify which frame ind…'
complete -c avifdec -l progressive -d 'Enable progressive AVIF processing'
complete -c avifdec -l no-strict -d 'Disable strict decoding, which disables strict validation checks and errors'
complete -c avifdec -s i -l info -d 'Decode all frames and display all image information instead of saving to disk'
complete -c avifdec -l ignore-icc -d 'If the input file contains an embedded ICC profile, ignore it (no-op if absen…'
complete -c avifdec -l size-limit -d 'Specifies the image size limit (in total pixels) that should be tolerated'
complete -c avifdec -l dimension-limit -d 'Specifies the image dimension limit (width or height) that should be tolerated'

