# bzz
# Autogenerated from man page /usr/share/man/man1/bzz.1.gz
complete -c bzz -s d -d 'Decoding mode'
complete -c bzz -s e -d 'compresses the data from file inputfile  and writes the compressed data into …'

