# c44
# Autogenerated from man page /usr/share/man/man1/c44.1.gz
complete -c c44 -o slice -d 'Specify the number of slices in each chunk'
complete -c c44 -o size -d 'Specify size targets for each chunk expressed in bytes'
complete -c c44 -o bpp -d 'Specify size targets for each chunk expressed in bits-per-pixel'
complete -c c44 -o percent -d 'Specify size targets for each chunk expressed as a percentage of the input fi…'
complete -c c44 -o decibel -d 'Specify quality targets for each chunk expressed as a comma-separated list of…'
complete -c c44 -o dbfrac -d 'Indicate that the decibel values specified in option'
complete -c c44 -o dpi -d 'Specify the resolution information encoded into the output file expressed in …'
complete -c c44 -o gamma -d 'Specify the gamma correction information encoded into the output file'
complete -c c44 -o mask -d 'The design of the '
complete -c c44 -o crcbnormal -d 'Select normal chrominance encoding'
complete -c c44 -o crcbhalf -d 'Selects half resolution chrominance encoding'
complete -c c44 -o crcbdelay -d 'This option can be used with '
complete -c c44 -o crcbfull -d 'Select the highest possible quality for encoding the chrominance information'
complete -c c44 -o crcbnone -d 'Disable the encoding of the chrominance'

