# calamares
# Autogenerated from man page /usr/share/man/man8/calamares.8.gz
complete -c calamares -s h -l help -d 'Displays this help'
complete -c calamares -s v -l version -d 'Displays version information'
complete -c calamares -s d -l debug -d 'Debugging mode for testing purposes.  Implies -D8 and -c'
complete -c calamares -s D -d 'Sets logging-level.  Higher numbers are more verbose'
complete -c calamares -s c -l config -d 'Configuration directory to use, for testing purposes'
complete -c calamares -s X -l xdg-config -d 'Use XDG environment variables for file lookup'
complete -c calamares -s T -l debug-translation -d 'Use translations from current directory'

