# cargo-logout
# Autogenerated from man page /usr/share/man/man1/cargo-logout.1.gz
complete -c cargo-logout -l registry
complete -c cargo-logout -s v
complete -c cargo-logout -l verbose
complete -c cargo-logout -s q
complete -c cargo-logout -l quiet
complete -c cargo-logout -l color
complete -c cargo-logout -l config
complete -c cargo-logout -s C
complete -c cargo-logout -s h
complete -c cargo-logout -l help
complete -c cargo-logout -s Z

