# cargo-remove
# Autogenerated from man page /usr/share/man/man1/cargo-remove.1.gz
complete -c cargo-remove -l dev
complete -c cargo-remove -l build
complete -c cargo-remove -l target
complete -c cargo-remove -l dry-run
complete -c cargo-remove -s v
complete -c cargo-remove -l verbose
complete -c cargo-remove -s q
complete -c cargo-remove -l quiet
complete -c cargo-remove -l color
complete -c cargo-remove -l manifest-path
complete -c cargo-remove -l locked
complete -c cargo-remove -l offline
complete -c cargo-remove -l frozen
complete -c cargo-remove -s p
complete -c cargo-remove -l package
complete -c cargo-remove -l config
complete -c cargo-remove -s C
complete -c cargo-remove -s h
complete -c cargo-remove -l help
complete -c cargo-remove -s Z

