# check_hd
# Autogenerated from man page /usr/share/man/man1/check_hd.1.gz
complete -c check_hd -l check -d 'do a lot of checks and remove unnecessary data'
complete -c check_hd -l sort -d 'sort data'
complete -c check_hd -l reverse -d 'reverse sorting order'
complete -c check_hd -l split -d 'write separate entries for each key'
complete -c check_hd -l with-source -d 'add comment to each item indicating info source'
complete -c check_hd -l mini -d 'minimal data base (basically driver info only)'
complete -c check_hd -l join-keys-first -d 'when combining similar items, join entries with common keys first (default is…'
complete -c check_hd -l cfile -d 'create C file to be included in libhd'
complete -c check_hd -l no-compact -d 'don\'t try to make C version as small as possible'
complete -c check_hd -l out -d 'write results to file, default is "hd. ids"'
complete -c check_hd -l log -d 'write log info to file, default is "hd'

