# clear
# Autogenerated from man page /usr/share/man/man1/clear.1.gz
complete -c clear -s T -d '-T type produces instructions suitable for the terminal type'
complete -c clear -s V -d 'reports the version of \\%ncurses associated with this program and exits with …'
complete -c clear -s x -d 'prevents %clear from attempting to clear the scrollback buffer'

