# composefs-info
# Autogenerated from man page /usr/share/man/man1/composefs-info.1.gz
complete -c composefs-info -l basedir -d 'This should point to a directory of backing files, and will be used by the mi…'

