# convert_hd
# Autogenerated from man page /usr/share/man/man1/convert_hd.1.gz
complete -c convert_hd -l ids -d 'write internal format (default) to "hd. ids"'
complete -c convert_hd -l no-ids -d 'do not write internal format'
complete -c convert_hd -l xml -d 'write XML to "hd. xml", DTD to "hd. dtd"'
complete -c convert_hd -l no-xml -d 'do not write XML (default)'
complete -c convert_hd -l with-source -d 'add comment to each item indicating info source'
complete -c convert_hd -l internal-dtd -d 'generate internal dtd Note: for more sophisticated operations on hardware dat…'

