# cpaldjvu
# Autogenerated from man page /usr/share/man/man1/cpaldjvu.1.gz
complete -c cpaldjvu -o dpi -d 'Specify the resolution information encoded into the output file expressed in …'
complete -c cpaldjvu -o colors -d 'Specify a maximum number of distinct colors for the color quantization algori…'
complete -c cpaldjvu -o bgwhite -d 'Cause the background layer to use the lightest quantified color instead of th…'
complete -c cpaldjvu -o verbose -d 'Display informational messages while running'

