# cracklib-check
# Autogenerated from man page /usr/share/man/man8/cracklib-check.8.gz
complete -c cracklib-check -l no-echo -d 'Don\'t echo the password which is ok to the terminal'
complete -c cracklib-check -s h -l help -d 'Print help explaining the command line options'

