# csepdjvu
# Autogenerated from man page /usr/share/man/man1/csepdjvu.1.gz
complete -c csepdjvu -s d -d 'Specify the resolution information encoded into the output file expressed in …'
complete -c csepdjvu -s q -d 'Specify the encoding quality of the IW44 encoded background layer'
complete -c csepdjvu -s t -d 'Program   csepdjvu interprets certain comments in the separated file to const…'
complete -c csepdjvu -s v -d 'Display a brief message describing each page'
complete -c csepdjvu -o slice -d 'of program c44 '
complete -c csepdjvu -o vv -d 'Display extensive informational messages during encoding'

