# cxl-destroy-region
# Autogenerated from man page /usr/share/man/man1/cxl-destroy-region.1.gz
complete -c cxl-destroy-region -s b -l bus
complete -c cxl-destroy-region -s f -l force
complete -c cxl-destroy-region -s d -l decoder
complete -c cxl-destroy-region -l debug

