# cxl-wait-sanitize
# Autogenerated from man page /usr/share/man/man1/cxl-wait-sanitize.1.gz
complete -c cxl-wait-sanitize -s b -l bus
complete -c cxl-wait-sanitize -s t -l timeout
complete -c cxl-wait-sanitize -s v -l verbose

