# cxl-create-region
# Autogenerated from man page /usr/share/man/man1/cxl-create-region.1.gz
complete -c cxl-create-region -s b -l bus
complete -c cxl-create-region -s m -l memdevs
complete -c cxl-create-region -s s -l size
complete -c cxl-create-region -s t -l type
complete -c cxl-create-region -s U -l uuid
complete -c cxl-create-region -s w -l ways
complete -c cxl-create-region -s g -l granularity
complete -c cxl-create-region -s d -l decoder
complete -c cxl-create-region -s Q -l enforce-qos
complete -c cxl-create-region -s u -l human
complete -c cxl-create-region -l debug

