# cxl-free-dpa
# Autogenerated from man page /usr/share/man/man1/cxl-free-dpa.1.gz
complete -c cxl-free-dpa -s S -l serial
complete -c cxl-free-dpa -s b -l bus
complete -c cxl-free-dpa -s d -l decoder
complete -c cxl-free-dpa -s t -l type
complete -c cxl-free-dpa -s f -l force
complete -c cxl-free-dpa -s v

