# cxl-monitor
# Autogenerated from man page /usr/share/man/man1/cxl-monitor.1.gz
complete -c cxl-monitor -s l -l log
complete -c cxl-monitor -l daemon
complete -c cxl-monitor -s v -l verbose
complete -c cxl-monitor -s u -l human

