# cxl-update-firmware
# Autogenerated from man page /usr/share/man/man1/cxl-update-firmware.1.gz
complete -c cxl-update-firmware -s b -l bus
complete -c cxl-update-firmware -s F -l firmware-file
complete -c cxl-update-firmware -s c -l cancel
complete -c cxl-update-firmware -s w -l wait
complete -c cxl-update-firmware -s v -l verbose

