# cxl-reserve-dpa
# Autogenerated from man page /usr/share/man/man1/cxl-reserve-dpa.1.gz
complete -c cxl-reserve-dpa -s S -l serial
complete -c cxl-reserve-dpa -s b -l bus
complete -c cxl-reserve-dpa -s d -l decoder
complete -c cxl-reserve-dpa -s t -l type
complete -c cxl-reserve-dpa -s f -l force
complete -c cxl-reserve-dpa -s s -l size
complete -c cxl-reserve-dpa -s v

