# cxl-disable-region
# Autogenerated from man page /usr/share/man/man1/cxl-disable-region.1.gz
complete -c cxl-disable-region -s b -l bus
complete -c cxl-disable-region -s f -l force
complete -c cxl-disable-region -s d -l decoder
complete -c cxl-disable-region -l debug

