# cxl-set-alert-config
# Autogenerated from man page /usr/share/man/man1/cxl-set-alert-config.1.gz
complete -c cxl-set-alert-config -s S -l serial
complete -c cxl-set-alert-config -s L -l life-used-threshold
complete -c cxl-set-alert-config -l life-used-alert
complete -c cxl-set-alert-config -s O -l over-temperature-threshold
complete -c cxl-set-alert-config -l over-temperature-alert
complete -c cxl-set-alert-config -s U -l under-temperature-threshold
complete -c cxl-set-alert-config -l under-temperature-alert
complete -c cxl-set-alert-config -s V -l volatile-mem-err-threshold
complete -c cxl-set-alert-config -l volatile-mem-err-alert
complete -c cxl-set-alert-config -s P -l pmem-err-threshold
complete -c cxl-set-alert-config -l pmem-err-alert
complete -c cxl-set-alert-config -s v -l verbose

