# cxl-list
# Autogenerated from man page /usr/share/man/man1/cxl-list.1.gz
complete -c cxl-list -s m -l memdev
complete -c cxl-list -s s -l serial
complete -c cxl-list -s M -l memdevs
complete -c cxl-list -s i -l idle
complete -c cxl-list -s H -l health
complete -c cxl-list -s I -l partition
complete -c cxl-list -s A -l alert-config
complete -c cxl-list -s B -l buses
complete -c cxl-list -s b -l bus
complete -c cxl-list -s P -l ports
complete -c cxl-list -s p -l port
complete -c cxl-list -s S -l single
complete -c cxl-list -s E -l endpoints
complete -c cxl-list -s e -l endpoint
complete -c cxl-list -s D -l decoders
complete -c cxl-list -s d -l decoder
complete -c cxl-list -s T -l targets
complete -c cxl-list -s R -l regions
complete -c cxl-list -s X -l dax
complete -c cxl-list -s r -l region
complete -c cxl-list -s v -l verbose
complete -c cxl-list -o vv -d 'Everything -v provides, plus include disabled devices with --idle.  oc'
complete -c cxl-list -o vvv -d 'Everything -vv provides, plus enable'
complete -c cxl-list -l debug
complete -c cxl-list -s u -l human

