# dbmmanage
# Autogenerated from man page /usr/share/man/man1/dbmmanage.1.gz
complete -c dbmmanage -s d -d 'crypt hashing (default, except on Win32, Netware)'
complete -c dbmmanage -s m -d 'MD5 hashing (default on Win32, Netware)'
complete -c dbmmanage -s s -d 'SHA1 hashing'
complete -c dbmmanage -s p -d 'plaintext (not recommended)      . SS "Commands"'

