# ddjvu
# Autogenerated from man page /usr/share/man/man1/ddjvu.1.gz
complete -c ddjvu -o format -d 'Specify the output file formats'
complete -c ddjvu -o quality -d 'below) often produces much smaller files'
complete -c ddjvu -o page -d 'Specify which pages should be decoded'
complete -c ddjvu -o eachpage -d 'When this option is specified, program ddjvu generates one separate file per …'
complete -c ddjvu -o mode -d 'Selects which layers of the DjVu image should be rendered'
complete -c ddjvu -o skip -d 'Instead of aborting when encountering a corrupted page, this option causes dd…'
complete -c ddjvu -s 1
complete -c ddjvu -o subsample -d 'This is equivalent to option'
complete -c ddjvu -s n
complete -c ddjvu -o scale -d 'Specify a magnification factor relative to the resolution stored  in the DjVu…'
complete -c ddjvu -o size -d 'Specify the size of the full output image'
complete -c ddjvu -o aspect
complete -c ddjvu -o verbose -d 'Display informational messages describing the  structure of the DjVu image an…'
complete -c ddjvu -o segment -d 'Specify an image segment to render'
complete -c ddjvu -o foreground
complete -c ddjvu -o background -d and
complete -c ddjvu -o black -d 'are shorthands for the '

