# depmod
# Autogenerated from man page /usr/share/man/man8/depmod.8.gz
complete -c depmod -s A -d --quick
complete -c depmod -s b -d '--basedir basedir'
complete -c depmod -s o -d '--outdir outdir'
complete -c depmod -s C -d '--config file or directory'
complete -c depmod -s e -d --errsyms
complete -c depmod -s E -d '--symvers Module. symvers'
complete -c depmod -s F -d '--filesyms System. map'
complete -c depmod -s h -d --help
complete -c depmod -s n -d --show
complete -c depmod -s P -d 'Some architectures prefix symbols with an extraneous character.  This'
complete -c depmod -s v -d --verbose
complete -c depmod -s V -d --version
complete -c depmod -s w -d 'Warn on duplicate dependencies, aliases, symbol versions, etc'

