# djvm
# Autogenerated from man page /usr/share/man/man1/djvm.1.gz
complete -c djvm -s c -d 'Create a bundled DjVu document named  doc. djvu by collecting files  page1'
complete -c djvm -s i -d 'Modify the bundled DjVu document named  doc. djvu by inserting file  page'
complete -c djvm -s d -d 'Remove page  pagenum from the bundled multi-page DjVu document R doc. djvu '
complete -c djvm -s l -d 'List all component files in the multi-page DjVu document doc. djvu '

