# djvused
# Autogenerated from man page /usr/share/man/man1/djvused.1.gz
complete -c djvused -s v -d 'Cause   djvused  to print a command line prompt before reading commands and a…'
complete -c djvused -s f -d 'Cause  djvused to read commands from file R scriptfile '
complete -c djvused -s e -d 'Cause  djvused to execute the commands specified by the option argument R com…'
complete -c djvused -s s -d 'Cause   djvused to save the file   djvufile after executing the specified com…'
complete -c djvused -s u -d 'Cause  djvused to print hidden text and annotations as UTF-8  instead of enco…'
complete -c djvused -s n -d 'Cause  djvused  to disregard save commands'

