# djvuxml
# Autogenerated from man page /usr/share/man/man1/djvuxml.1.gz
complete -c djvuxml -l page -d 'Select a page in a multi-page document'
complete -c djvuxml -l with-text -d 'Specifies the  HIDDENTEXT  element for each page should be included in the ou…'
complete -c djvuxml -l with-anno -d 'flag then the'
complete -c djvuxml -l without-anno -d 'is implied.   If none of the  '
complete -c djvuxml -l without-text
complete -c djvuxml -s o -d 'In principle the target DjVu file is the file  referenced by the OBJECT  elem…'

