# djvutxt
# Autogenerated from man page /usr/share/man/man1/djvutxt.1.gz
complete -c djvutxt -l page -d 'Specify which pages should be processed'
complete -c djvutxt -l detail -d 'This options causes  djvutxt to output S-expressions  specifying the position…'
complete -c djvutxt -o detail -d and
complete -c djvutxt -o escape -d 'this program simply outputs the UTF-8 text.  Option'
complete -c djvutxt -l escape -d 'Output escape sequences of the form  "ooo" for all non ASCII or non printable…'

