# dump.erofs
# Autogenerated from man page /usr/share/man/man1/dump.erofs.1.gz
complete -c 'dump.erofs' -l device -d 'Specify an extra device to be used together'
complete -c 'dump.erofs' -l ls -d 'List directory contents.   NID or  path required'
complete -c 'dump.erofs' -l nid -d 'Specify an inode NID in order to print its file information'
complete -c 'dump.erofs' -l path -d 'Specify an inode path in order to print its file information'
complete -c 'dump.erofs' -s e -d 'Show the file extent information.   NID or  path required'
complete -c 'dump.erofs' -s V -l version -d 'Print the version number and exit'
complete -c 'dump.erofs' -s h -l help -d 'Display help string and exit'
complete -c 'dump.erofs' -s s -d 'Show superblock information.  This is the default if no options are specified'
complete -c 'dump.erofs' -s S -d 'Show image statistics, including file type/size distribution, number of (un)c…'

