# fastfetch
# Autogenerated from man page /usr/share/man/man1/fastfetch.1.gz
complete -c fastfetch -s h -l help -d 'Show help output, displaying all available options or help for given command'
complete -c fastfetch -s v -l version -d 'Show version of fastfetch'
complete -c fastfetch -l list-config-paths -d 'List search paths of config files'
complete -c fastfetch -l list-data-paths -d 'List search paths of presets and logos'
complete -c fastfetch -l list-logos -d 'List available logos, they can be loaded with --logo'
complete -c fastfetch -l list-modules -d 'List available modules'
complete -c fastfetch -l list-presets -d 'List available presets, they can be loaded with --config'
complete -c fastfetch -l list-features -d 'List the supported features fastfetch was compiled with'
complete -c fastfetch -l print-logos -d 'Print available logos'
complete -c fastfetch -l print-structure -d 'Print the default structure'
complete -c fastfetch -l format -d 'Set the output format'
complete -c fastfetch -s l -l logo -d 'Set the logo to display'
complete -c fastfetch -s s -l structure -d 'Set the structure of the fetch'
complete -c fastfetch -s c -l config -d 'Use the specified config file or preset'
complete -c fastfetch -l gen-config -d 'Generate a config file with options specified on the command line'
complete -c fastfetch -l gen-config-force -d 'Same as --gen-config, but overwrites existing config'

