# fixproc
# Autogenerated from man page /usr/share/man/man1/fixproc.1.gz
complete -c fixproc -o min -d 'minimum number of processes that should be running, defaults to 1'
complete -c fixproc -o max -d 'maximum number of processes that should be running, defaults to 1'
complete -c fixproc -o check -d 'check process against database /local/etc/fixproc. conf'
complete -c fixproc -o kill -d 'kill process, wait 5 seconds, kill -9 if still exist'
complete -c fixproc -o restart -d 'kill process, wait 5 seconds, kill -9 if still exist, then start again'
complete -c fixproc -o exist -d 'checks if proc exists in ps && (min <= num.  of processes <= max)'
complete -c fixproc -o fix -d 'check process against database /local/etc/fixproc. conf'

