# freerdp-shadow-cli3
# Autogenerated from man page /usr/share/man/man1/freerdp-shadow-cli3.1.gz
complete -c freerdp-shadow-cli3 -o auth -d 'Disable authentication'
complete -c freerdp-shadow-cli3 -o may-view -d 'Clients may view without prompt'
complete -c freerdp-shadow-cli3 -o may-interact -d 'Clients may interact without prompt'
complete -c freerdp-shadow-cli3 -o sec-rdp -d 'Disable RDP security (default:on)'
complete -c freerdp-shadow-cli3 -o sec-tls -d 'Disable TLS protocol security (default:on)'
complete -c freerdp-shadow-cli3 -o sec-nla -d 'Disable NLA protocol security (default:on)'

