# freerdp-proxy3
# Autogenerated from man page /usr/share/man/man1/freerdp-proxy3.1.gz
complete -c freerdp-proxy3 -s h -l help -d 'Display a help text explaining usage'
complete -c freerdp-proxy3 -l buildconfig -d 'Print the build configuration of the proxy and exit'
complete -c freerdp-proxy3 -s v -l version -d 'Print the version of the proxy and exit'
complete -c freerdp-proxy3 -l dump-config -d 'Dump a template configuration to <config-ini-file>'

