# fsck.erofs
# Autogenerated from man page /usr/share/man/man1/fsck.erofs.1.gz
complete -c 'fsck.erofs' -s V -l version -d 'Print the version number of fsck. erofs and exit'
complete -c 'fsck.erofs' -s d -d 'Specify the level of debugging messages'
complete -c 'fsck.erofs' -s p -d 'Print total compression ratio of all files including compressed and non-compr…'
complete -c 'fsck.erofs' -l device -d 'Specify an extra blob device to be used together'
complete -c 'fsck.erofs' -l extract -d 'Test to extract the whole file system'
complete -c 'fsck.erofs' -s h -l help -d 'Display help string and exit'
complete -c 'fsck.erofs' -s a -s A -s y -d 'These options do nothing at all; they are provided only for compatibility wit…'

