# git-lfs-prune
# Autogenerated from man page /usr/share/man/man1/git-lfs-prune.1.gz
complete -c git-lfs-prune -l dry-run -s d
complete -c git-lfs-prune -l force -s f
complete -c git-lfs-prune -l recent
complete -c git-lfs-prune -l verify-remote -s c
complete -c git-lfs-prune -l no-verify-remote
complete -c git-lfs-prune -l verify-reachable
complete -c git-lfs-prune -l no-verify-reachable
complete -c git-lfs-prune -l when-unverified
complete -c git-lfs-prune -l verbose -s v
complete -c git-lfs-prune -l verify-unreachable

