# git-lfs-install
# Autogenerated from man page /usr/share/man/man1/git-lfs-install.1.gz
complete -c git-lfs-install -l force
complete -c git-lfs-install -l local
complete -c git-lfs-install -l worktree
complete -c git-lfs-install -l manual
complete -c git-lfs-install -l system
complete -c git-lfs-install -l skip-smudge
complete -c git-lfs-install -l skip-repo
complete -c git-lfs-install -l global

