# git-lfs-pointer
# Autogenerated from man page /usr/share/man/man1/git-lfs-pointer.1.gz
complete -c git-lfs-pointer -l file
complete -c git-lfs-pointer -l pointer
complete -c git-lfs-pointer -l stdin
complete -c git-lfs-pointer -l check
complete -c git-lfs-pointer -l strict -l no-strict

