# git-refs
# Autogenerated from man page /usr/share/man/man1/git-refs.1.gz
complete -c git-refs -l ref-format -d 'The ref format to migrate the ref store to.  Can be one of: . sp'
complete -c git-refs -l dry-run -d 'Perform the migration, but do not modify the repository'

