# git-lfs-track
# Autogenerated from man page /usr/share/man/man1/git-lfs-track.1.gz
complete -c git-lfs-track -l verbose -s v
complete -c git-lfs-track -l dry-run -s d
complete -c git-lfs-track -l filename
complete -c git-lfs-track -l lockable -s l
complete -c git-lfs-track -l not-lockable
complete -c git-lfs-track -l no-excluded
complete -c git-lfs-track -l no-modify-attrs -d 'Makes matched entries stat-dirty so that Git can re-index files you wish to c…'

