# git-lfs-locks
# Autogenerated from man page /usr/share/man/man1/git-lfs-locks.1.gz
complete -c git-lfs-locks -s r -l remote
complete -c git-lfs-locks -s i -l id
complete -c git-lfs-locks -s p -l path
complete -c git-lfs-locks -l local
complete -c git-lfs-locks -l cached
complete -c git-lfs-locks -l verify
complete -c git-lfs-locks -s l -l limit
complete -c git-lfs-locks -l json

