# greetd
# Autogenerated from man page /usr/share/man/man1/greetd.1.gz
complete -c greetd -s c -l config -d 'Specifies the configuration file to use'
complete -c greetd -l vt -d 'The VT to use, overwriting the value from the configuration file.  This'

