# HEAD.1p
# Autogenerated from man page /usr/share/man/man1/HEAD.1p.gz
complete -c 'HEAD.1p' -s m
complete -c 'HEAD.1p' -s f
complete -c 'HEAD.1p' -s b
complete -c 'HEAD.1p' -s t
complete -c 'HEAD.1p' -s i
complete -c 'HEAD.1p' -s c
complete -c 'HEAD.1p' -s p
complete -c 'HEAD.1p' -s P
complete -c 'HEAD.1p' -s H
complete -c 'HEAD.1p' -s C
complete -c 'HEAD.1p' -s u
complete -c 'HEAD.1p' -s U
complete -c 'HEAD.1p' -s s
complete -c 'HEAD.1p' -s S
complete -c 'HEAD.1p' -s e
complete -c 'HEAD.1p' -s E
complete -c 'HEAD.1p' -s d
complete -c 'HEAD.1p' -s o
complete -c 'HEAD.1p' -s v
complete -c 'HEAD.1p' -s h
complete -c 'HEAD.1p' -s a

