# heif-info
# Autogenerated from man page /usr/share/man/man1/heif-info.1.gz
complete -c heif-info -s d -l dump-boxes -d 'Show a low-level dump of all MP4 file boxes'
complete -c heif-info -s h -l help -d 'Show help.  A filename is not required or used'
complete -c heif-info -s v -l version -d 'Show version information for the tool, library version, and the plugin path'

