# hwinfo
# Autogenerated from man page /usr/share/man/man8/hwinfo.8.gz
complete -c hwinfo -l '<\\fHARDWARE_ITEM>' -d 'This option can be given more than once'
complete -c hwinfo -l short -d 'Show only a summary'
complete -c hwinfo -l listmd -d 'Normally hwinfo does not report RAID devices.  Add this option to see them'
complete -c hwinfo -l only -d 'This option can be given more than once'
complete -c hwinfo -l save-config -d 'Store config for a particular device below /var/lib/hardware'
complete -c hwinfo -l show-config -d 'Show saved config data for a particular device'
complete -c hwinfo -l map -d 'If disk names have changed (e. g'
complete -c hwinfo -l debug -d 'Set debug level to N.  The debug info is shown only in the log file'
complete -c hwinfo -l verbose -d 'Increase verbosity.  Only together with --map'
complete -c hwinfo -l log -d 'Write log info to FILE'
complete -c hwinfo -l dump-db -d 'Dump hardware data base'
complete -c hwinfo -l version -d 'Print libhd version'
complete -c hwinfo -l '<HARDWARE_ITEM>' -d 'This option can be given more than once'
complete -c hwinfo -l help -d 'Print usage'

