# infotocap.1m
# Autogenerated from man page /usr/share/man/man1/infotocap.1m.gz
complete -c 'infotocap.1m' -s C -d 'option implied.  You can use other %tic options such as'
complete -c 'infotocap.1m' -s 1
complete -c 'infotocap.1m' -s f
complete -c 'infotocap.1m' -s v
complete -c 'infotocap.1m' -s w -d and
complete -c 'infotocap.1m' -s x -d 'The -V option reports the version of %ncurses associated with this program an…'

