# kbuildsycoca6
# Autogenerated from man page /usr/share/man/man8/kbuildsycoca6.8.gz
complete -c kbuildsycoca6 -l global -d 'Ignores any user-set files (in XDG_DATA_HOME)'
complete -c kbuildsycoca6 -l noincremental -d 'Rather than using the existing cache and only updating the information that h…'
complete -c kbuildsycoca6 -l menutest -d 'Test the generation of the application menu database'
complete -c kbuildsycoca6 -l testmode -d 'Use the QStandardPaths "test mode" to avoid interfering with user data'
complete -c kbuildsycoca6 -l track -d 'Track a menu ID for debugging'
complete -c kbuildsycoca6 -l author -d 'Show author information'
complete -c kbuildsycoca6 -l license -d 'Show license information'
complete -c kbuildsycoca6 -s h -l help -d 'Show a brief help text'
complete -c kbuildsycoca6 -s v -l version -d 'Show version information'

