# libinput-analyze-buttons
# Autogenerated from man page /usr/share/man/man1/libinput-analyze-buttons.1.gz
complete -c libinput-analyze-buttons -l help -d 'Print help'
complete -c libinput-analyze-buttons -l threshold -d 'Color any delta time less than the threshold in red'

