# lsinitcpio
# Autogenerated from man page /usr/share/man/man1/lsinitcpio.1.gz
complete -c lsinitcpio -s a -l analyze
complete -c lsinitcpio -s c -l config
complete -c lsinitcpio -s l -l list
complete -c lsinitcpio -s x -l extract
complete -c lsinitcpio -s h -l help
complete -c lsinitcpio -s n -l nocolor
complete -c lsinitcpio -s V -l version
complete -c lsinitcpio -s v -l verbose
complete -c lsinitcpio -l cpio
complete -c lsinitcpio -l early

