# lwp-dump.1p
# Autogenerated from man page /usr/share/man/man1/lwp-dump.1p.gz
complete -c 'lwp-dump.1p' -l agent
complete -c 'lwp-dump.1p' -l keep-client-headers
complete -c 'lwp-dump.1p' -l max-length
complete -c 'lwp-dump.1p' -l method
complete -c 'lwp-dump.1p' -l parse-head
complete -c 'lwp-dump.1p' -l request

