# malcontent-client
# Autogenerated from man page /usr/share/man/man8/malcontent-client.8.gz
complete -c malcontent-client -s q -l quiet -d 'Only output error messages, and no informational messages, as the operation p…'
complete -c malcontent-client -s n -l no-interactive -d 'Do not allow interactive authorization with polkit'
complete -c malcontent-client -l allow-user-installation -d 'Allow the user to install flatpaks to their user repository'
complete -c malcontent-client -l disallow-user-installation -d 'Disallow the user from installing flatpaks to their user repository'
complete -c malcontent-client -l allow-system-installation -d 'Allow the user to install flatpaks to the system repository'
complete -c malcontent-client -l disallow-system-installation -d 'Disallow the user from installing flatpaks to the system repository'
complete -c malcontent-client -l now -d 'Check session limits (in particular, session expiry time) against the given d…'

