# mib2c
# Autogenerated from man page /usr/share/man/man1/mib2c.1.gz
complete -c mib2c -s h -d 'Display a help message'
complete -c mib2c -s c -d 'Use CONFIGFILE when generating code'
complete -c mib2c -s I -d 'Search for configuration files in PATH'
complete -c mib2c -s f -d 'Places the output code into OUTNAME. c and OUTNAME. h'
complete -c mib2c -s i -d 'Do not run indent on the resulting code'
complete -c mib2c -s s -d 'Do not look for MIBNODE. sed and run sed on the resulting code'
complete -c mib2c -s q -d 'Run in "quiet" mode, which minimizes the status messages mib2c generates'

