# mkarchiso
# Autogenerated from man page /usr/share/man/man1/mkarchiso.1.gz
complete -c mkarchiso -s A -d 'nf Set an application name for the ISO.  Default: \'mkarchiso iso\'. fi . sp'
complete -c mkarchiso -s C -d 'nf pacman configuration file.  Default: /etc/pacman. conf. fi . sp'
complete -c mkarchiso -s D -d 'nf Set an install_dir.  All files will be located here.  Default: arch'
complete -c mkarchiso -s L -d 'nf Set the ISO volume label.  Default: MKARCHISO. fi . sp'
complete -c mkarchiso -s P -d 'nf Set the ISO publisher.  Default: mkarchiso. fi . sp'
complete -c mkarchiso -s c -d 'nf Provide certificates for codesigning of netboot artifacts as well as the r…'
complete -c mkarchiso -s g -d 'nf Set the PGP key ID to be used for signing the rootfs image'
complete -c mkarchiso -s G -d 'nf Set the PGP signer (must include an email address)'
complete -c mkarchiso -s h -d 'nf Help message. fi . sp'
complete -c mkarchiso -s m -d 'nf Build mode(s) to use (valid modes are: bootstrap, iso and netboot)'
complete -c mkarchiso -s o -d 'nf Set the output directory.  Default: . /out. fi . sp'
complete -c mkarchiso -s p -d 'nf Package(s) to install'
complete -c mkarchiso -s r -d 'nf Delete the working directory at the end. fi . sp'
complete -c mkarchiso -s v -d 'nf Enable verbose output. fi . sp'
complete -c mkarchiso -s w -d 'nf Set the working directory.  Default: . /work. fi . sp'

