# mkinitcpio
# Autogenerated from man page /usr/share/man/man8/mkinitcpio.8.gz
complete -c mkinitcpio -s A -l addhooks
complete -c mkinitcpio -s c -l config
complete -c mkinitcpio -s d -l generatedir
complete -c mkinitcpio -s D -l hookdir
complete -c mkinitcpio -s g -l generate
complete -c mkinitcpio -s H -l hookhelp
complete -c mkinitcpio -s h -l help
complete -c mkinitcpio -s k -l kernel
complete -c mkinitcpio -s L -l listhooks
complete -c mkinitcpio -s M -l automods
complete -c mkinitcpio -s n -l nocolor
complete -c mkinitcpio -s U -l uki
complete -c mkinitcpio -s P -l allpresets
complete -c mkinitcpio -s p -l preset
complete -c mkinitcpio -s R -l remove
complete -c mkinitcpio -s r -l moduleroot
complete -c mkinitcpio -s S -l skiphooks
complete -c mkinitcpio -s s -l save
complete -c mkinitcpio -s t -l builddir
complete -c mkinitcpio -s V -l version
complete -c mkinitcpio -s v -l verbose
complete -c mkinitcpio -s z -l compress
complete -c mkinitcpio -l cmdline
complete -c mkinitcpio -l no-cmdline
complete -c mkinitcpio -l splash
complete -c mkinitcpio -l uefistub
complete -c mkinitcpio -l ukiconfig
complete -c mkinitcpio -l no-ukify
complete -c mkinitcpio -l kernelimage
complete -c mkinitcpio -l osrelease

