# modinfo
# Autogenerated from man page /usr/share/man/man8/modinfo.8.gz
complete -c modinfo -s F -d '--field field'
complete -c modinfo -s b -d '--basedir basedir'
complete -c modinfo -s k -d 'Provide information about a kernel other than the running one.  This is'
complete -c modinfo -s 0 -d --null
complete -c modinfo -s a -l author -d '-d --description'

