# modprobe
# Autogenerated from man page /usr/share/man/man8/modprobe.8.gz
complete -c modprobe -s b -d --use-blacklist
complete -c modprobe -s C -d '--config directory'
complete -c modprobe -s c -d --showconfig
complete -c modprobe -l dump-modversions -d 'Print out a list of module versioning information required by a module'
complete -c modprobe -s d -d --dirname
complete -c modprobe -l first-time -d 'Normally, modprobe will succeed (and do nothing) if told to insert a'
complete -c modprobe -l force-vermagic -d 'Every module contains a small string containing important information,'
complete -c modprobe -l force-modversion -d 'When modules are compiled with CONFIG_MODVERSIONS set, a section'
complete -c modprobe -s f -d --force
complete -c modprobe -s i -d --ignore-install
complete -c modprobe -s n -d --dry-run
complete -c modprobe -s q -d --quiet
complete -c modprobe -s R -d --resolve-alias
complete -c modprobe -s r -d --remove
complete -c modprobe -s w -d '--wait TIMEOUT_MSEC'
complete -c modprobe -s S -d '--set-version version'
complete -c modprobe -l show-depends -d 'List the dependencies of a module (or alias), including the module'
complete -c modprobe -s s -d --syslog
complete -c modprobe -s V -d --version
complete -c modprobe -s v -d --verbose

