# nasm
# Autogenerated from man page /usr/share/man/man1/nasm.1.gz
complete -c nasm -s @ -d 'Causes nasm to process options from filename as if they were included on the …'
complete -c nasm -s a -d 'Causes nasm to assemble the given input file without first applying the macro…'
complete -c nasm -s D -s d -d 'Pre-defines a single-line macro'
complete -c nasm -s E -s e -d 'Causes nasm to preprocess the given input file, and write the output to stdou…'
complete -c nasm -s f -d 'Specifies the output file format'
complete -c nasm -s F -d 'Specifies the debug information format'
complete -c nasm -s g -d 'Causes nasm to generate debug information'
complete -c nasm -o gformat -d 'Equivalent to -g -F format'
complete -c nasm -s h -d 'Causes nasm to exit immediately, after giving a summary of its invocation opt…'
complete -c nasm -o hf -d 'Same as -h , but also lists all valid output formats'
complete -c nasm -s I -s i -d 'Adds a directory to the search path for include files'
complete -c nasm -s l -d 'Causes an assembly listing to be directed to the given file, in which the ori…'
complete -c nasm -s M -d 'Causes nasm to output Makefile-style dependencies to stdout; normal output is…'
complete -c nasm -o MG -d 'Same as -M but assumes that missing Makefile dependencies are generated and a…'
complete -c nasm -o MF -d 'Output Makefile-style dependencies to the specified file'
complete -c nasm -o MD -d 'Same as a combination of -M and -MF options'
complete -c nasm -o MT -d 'Override the default name of the dependency target dependency target name'
complete -c nasm -o MQ -d 'The same as -MT except it tries to quote characters that have special meaning…'
complete -c nasm -o MP -d 'Emit phony target'
complete -c nasm -s O -d 'Optimize branch offsets. sp'
complete -c nasm -s o -d 'Specifies a precise name for the output file, overriding nasm\\*(Aqs default m…'
complete -c nasm -s P -s p -d 'Specifies a file to be pre-included, before the main source file starts to be…'
complete -c nasm -s s -d 'Causes nasm to send its error messages and/or help text to stdout instead of …'
complete -c nasm -s t -d 'Causes nasm to assemble in SciTech TASM compatible mode'
complete -c nasm -s U -s u -d 'Undefines a single-line macro'
complete -c nasm -s v -d 'Causes nasm to exit immediately, after displaying its version number'
complete -c nasm -o wfoo -d 'Causes nasm to enable or disable certain classes of warning messages, for exa…'
complete -c nasm -s X -d 'Specifies error reporting format (gnu or vc)'
complete -c nasm -s y -d 'Causes nasm to list supported debug formats'
complete -c nasm -s Z -d 'Causes nasm to redirect error messages to filename'
complete -c nasm -l prefix -l postfix -d 'Prepend or append (respectively) the given argument to all global or extern v…'
complete -c nasm -o felf
complete -c nasm -o O0 -d 'oc o 2. 3'
complete -c nasm -o O1 -d 'oc o 2. 3'
complete -c nasm -o Ox
complete -c nasm -o Wlabel-orphan -d or
complete -c nasm -o Wno-orphan-labels
complete -c nasm -o w+label-orphan -d or
complete -c nasm -o w-macro-params

