# ostree-admin-post-copy
# Autogenerated from man page /usr/share/man/man1/ostree-admin-post-copy.1.gz
complete -c ostree-admin-post-copy -l sysroot -d 'Path to the system to use rather than the current one'

