# ostree-admin-status
# Autogenerated from man page /usr/share/man/man1/ostree-admin-status.1.gz
complete -c ostree-admin-status -l sysroot -d 'Create a new OSTree sysroot at PATH'
complete -c ostree-admin-status -s V -l verify -d 'Print the commit verification status'
complete -c ostree-admin-status -s S -l skip-signatures -d 'Skip signatures in output'
complete -c ostree-admin-status -s D -l is-default -d 'Output the string default if the default deployment is the booted one, not-de…'
complete -c ostree-admin-status -s v -l verbose -d 'Print debug information during command processing'
complete -c ostree-admin-status -l version -d 'Print version information and exit'

