# ostree-admin-lock-finalization
# Autogenerated from man page /usr/share/man/man1/ostree-admin-lock-finalization.1.gz
complete -c ostree-admin-lock-finalization -l sysroot -d 'Path to the system to use rather than the current one'
complete -c ostree-admin-lock-finalization -l unlock -s u -d 'Unlock the deployment finalization state'
complete -c ostree-admin-lock-finalization -l lock-finalization -d 'argument for ostree admin deploy, which is the recommended way to use this fe…'

