# ostree-admin-init-fs
# Autogenerated from man page /usr/share/man/man1/ostree-admin-init-fs.1.gz
complete -c ostree-admin-init-fs -l modern -d 'Equivalent to --epoch=1'
complete -c ostree-admin-init-fs -l epoch -d 'This accepts an integer value in the range [0-1], inclusive'

