# paper
# Autogenerated from man page /usr/share/man/man1/paper.1.gz
complete -c paper -l all -d 'show information about all known paper sizes'
complete -c paper -l no-size -d 'do not show paper sizes (width followed by height)'
complete -c paper -l unit -d 'unit in which to show sizes [pt, mm, in; default: natural units]'
complete -c paper -l help -d 'display this help message and exit'
complete -c paper -l version -d 'display version information and exit'

