# pw-container
# Autogenerated from man page /usr/share/man/man1/pw-container.1.gz
complete -c pw-container -s P -l properties -d 'Set extra context properties as a JSON object'
complete -c pw-container -s r -l remote -d 'The name the remote instance to connect to'
complete -c pw-container -s h -l help -d 'Show help'
complete -c pw-container -l version -d 'Show version information'

