# sane-config
# Autogenerated from man page /usr/share/man/man1/sane-config.1.gz
complete -c sane-config -l version -d 'Print the currently installed version of libsane on the standard output'
complete -c sane-config -l help -d 'Print a short usage message'
complete -c sane-config -l libs -d 'Print the additional libraries that are necessary to link a SANE frontend to …'
complete -c sane-config -l ldflags -d 'Print the linker flags that are necessary to link a SANE frontend to libsane'
complete -c sane-config -l cflags -d 'Print the compiler flags that are necessary to compile a SANE frontend'
complete -c sane-config -l prefix -d 'Print the prefix used during compilation of libsane'
complete -c sane-config -l exec-prefix -d 'Print the exec-prefix used during compilation of libsane'

