# slirpvde
# Autogenerated from man page /usr/share/man/man1/slirpvde.1.gz
complete -c slirpvde -s s -l sock -l socket -l vdesock -l unix -d 'specify the VDE switch directory (default /var/run/vde. ctl)'
complete -c slirpvde -s p -l pidfile -d 'specify the name of the file which contains the PID of slirpvde'
complete -c slirpvde -s g -l group -d 'specify the UNIX group for the VDE communication socket'
complete -c slirpvde -s m -l mod -d 'specify the octal UNIX permissions for the VDE communication socket'
complete -c slirpvde -s P -l port -d 'specify the port of the vde switch whern slirpvde must be connected'
complete -c slirpvde -s d -l daemon -d 'detach from terminal and run slirpvde in background'
complete -c slirpvde -s H -l host -d 'specify the host address (default 10. 0. 2. 2/24)'
complete -c slirpvde -s n -l network -d 'specify the network address (default 10. 0. 2. 0/24)'
complete -c slirpvde -s N -l dns -d 'Specify the address of the dns server'
complete -c slirpvde -s D -l dhcp -d 'turn on the DHCP server for the network autoconfiguration of all the units co…'
complete -c slirpvde -s L -d 'specifyes a TCP port redirection'
complete -c slirpvde -s U -d 'specifyes a UDP port redirection'
complete -c slirpvde -s X -d 'redirect a X window screen of a virtual machine'
complete -c slirpvde -s x -d 'redirect a port of the virtual router (usually 10. 0. 2'
complete -c slirpvde -s t -l tftp -d 'slirpvde enables a tftp server sharing (read-only) the directory at pathname'
complete -c slirpvde -s q -l quiet -d 'Quiet;   do   not  write  anything  to  standard  output'

