# snmpbulkget
# Autogenerated from man page /usr/share/man/man1/snmpbulkget.1.gz
complete -c snmpbulkget -o Cn -d 'Set the  non-repeaters field in the GETBULK PDU'
complete -c snmpbulkget -o Cr -d 'Set the max-repetitions field in the GETBULK PDU'

