# snmpnetstat
# Autogenerated from man page /usr/share/man/man1/snmpnetstat.1.gz
complete -c snmpnetstat -o CL -d 'use the legacy SNMP MIB elements, not the modern IP version agnostic tables'
complete -c snmpnetstat -o Ca -d 'With the default display, show the state of all sockets; normally sockets use…'
complete -c snmpnetstat -o Cf -d 'Only show entries for the selected address family (inet, inet6)'
complete -c snmpnetstat -o Ci -d 'Show the state of all of the network interfaces'
complete -c snmpnetstat -o Cd -d 'Add dropped packets to the interface display'
complete -c snmpnetstat -o Cb -d 'Show an extended interface status, giving octets in addition to packets'
complete -c snmpnetstat -o Co -d 'Show an abbreviated interface status, giving octets in place of packets'
complete -c snmpnetstat -o CI -d 'Show information only about this interface; used with an interval as describe…'
complete -c snmpnetstat -o Cn -d 'Show network addresses as numbers (normally  snmpnetstat interprets addresses…'
complete -c snmpnetstat -o Cv -d 'Allow long host or service names to break the columnar output'
complete -c snmpnetstat -o Cp -d 'Show statistics about  protocol, which is either a well-known name for a prot…'
complete -c snmpnetstat -o Cs -d 'Show per-protocol statistics'
complete -c snmpnetstat -o Cr -d 'Show the routing tables'
complete -c snmpnetstat -o CR -d 'For GETBULK requests, repeaters specifies the max-repeaters value to use'

