# snmpps
# Autogenerated from man page /usr/share/man/man1/snmpps.1.gz
complete -c snmpps -o Cp -d 'Show hrSWRunPath in addition to hrSWRunName'
complete -c snmpps -o Ca -d 'Show hrSWRunParameters in addition to hrSWRunName'
complete -c snmpps -o Ct -d 'Sort display by total CPU usage'
complete -c snmpps -o Cm -d 'Sort display by memory usage'

