# sqlhist
# Autogenerated from man page /usr/share/man/man1/sqlhist.1.gz
complete -c sqlhist -s n -d 'The name of the synthetic event to create'
complete -c sqlhist -s t -d 'In order to test this out as non root user, a copy of the tracefs directory c…'
complete -c sqlhist -s e -d 'Not only display the commands to create the histogram, but also execute them'
complete -c sqlhist -s f -d 'Instead of reading the SQL commands from the command line, read them from file'
complete -c sqlhist -s m -d 'Do the given action when the variable var hits a new maximum'
complete -c sqlhist -s c -d 'Do the given action when the variable var changes its value'
complete -c sqlhist -s s -d 'Perform a snapshot instead of calling the synthetic event'
complete -c sqlhist -s T -d 'Perform both a snapshot and trace the synthetic event'
complete -c sqlhist -s S -d 'Save the given fields'
complete -c sqlhist -s B -d 'For simple statements that only produce a histogram, the instance given here …'
complete -c sqlhist -s R

