# systemd-id128
# Autogenerated from man page /usr/share/man/man1/systemd-id128.1.gz
complete -c systemd-id128 -s p -l pretty -d 'Generate output as programming language snippets. sp Added in version 240'
complete -c systemd-id128 -s P -l value -d 'Only print the value.  May be combined with -u/--uuid'
complete -c systemd-id128 -s a -l app-specific -d 'With this option, identifiers will be printed that are the result of hashing …'
complete -c systemd-id128 -s u -l uuid -d 'Generate output as a UUID formatted in the "canonical representation", with f…'
complete -c systemd-id128 -l no-pager -d 'Do not pipe output into a pager'
complete -c systemd-id128 -l no-legend -d 'Do not print the legend, i. e.  column headers and the footer with hints'
complete -c systemd-id128 -l json -d 'Shows output formatted as JSON'
complete -c systemd-id128 -s j -d 'Equivalent to --json=pretty if running on a terminal, and --json=short otherw…'
complete -c systemd-id128 -s h -l help -d 'Print a short help text and exit'
complete -c systemd-id128 -l version -d 'Print a short version string and exit'
complete -c systemd-id128 -o u/--uuid

