# systemd-vpick
# Autogenerated from man page /usr/share/man/man1/systemd-vpick.1.gz
complete -c systemd-vpick -l basename -s B -d 'Overrides the "basename" of the files to look for, i. e'
complete -c systemd-vpick -s V -d 'Explicitly configures the version to select'
complete -c systemd-vpick -s A -d 'Explicitly configures the architecture to select'
complete -c systemd-vpick -l suffix -s S -d 'Configures the suffix of the filenames to consider.  For the "'
complete -c systemd-vpick -l type -s t -d 'Configures the inode type to look for in the ". v/" directory'
complete -c systemd-vpick -l print -s p -d 'Configures what precisely to write to standard output'
complete -c systemd-vpick -l resolve -d 'Takes a boolean argument'
complete -c systemd-vpick -s h -l help -d 'Print a short help text and exit'
complete -c systemd-vpick -l version -d 'Print a short version string and exit'

