# systemd-tmpfiles
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles.8.gz
complete -c systemd-tmpfiles -l create
complete -c systemd-tmpfiles -l remove
complete -c systemd-tmpfiles -l clean
complete -c systemd-tmpfiles -l replace -d 'is specified, arguments specified on the command line are used instead of the…'
complete -c systemd-tmpfiles -l purge
complete -c systemd-tmpfiles -l dry-run -d '(see below) to verify which files and directories will be deleted'
complete -c systemd-tmpfiles -l user
complete -c systemd-tmpfiles -l boot
complete -c systemd-tmpfiles -l graceful
complete -c systemd-tmpfiles -l prefix
complete -c systemd-tmpfiles -l exclude-prefix
complete -c systemd-tmpfiles -s E
complete -c systemd-tmpfiles -l root
complete -c systemd-tmpfiles -l image
complete -c systemd-tmpfiles -l image-policy
complete -c systemd-tmpfiles -l cat-config
complete -c systemd-tmpfiles -l tldr
complete -c systemd-tmpfiles -l no-pager
complete -c systemd-tmpfiles -s h -l help
complete -c systemd-tmpfiles -l version

