# tdbdump
# Autogenerated from man page /usr/share/man/man8/tdbdump.8.gz
complete -c tdbdump -s h -d 'Get help information'
complete -c tdbdump -s k -d 'The -k option restricts dumping to a single key, if found'
complete -c tdbdump -s e -d 'The -e tries to dump out from a corrupt database'
complete -c tdbdump -s x -d 'The -x changes the output data to a hex dump, from the default mix of ASCII a…'

