# toe.1m
# Autogenerated from man page /usr/share/man/man1/toe.1m.gz
complete -c 'toe.1m' -s u -d '-a lists entries from all terminal database directories that terminfo would s…'
complete -c 'toe.1m' -s s -d '\\%toe does not attempt to merge duplicates in its report'
complete -c 'toe.1m' -s h -d 'writes a heading naming each each directory as it is accessed'
complete -c 'toe.1m' -s U -d 'lists terminal type reverse dependencies in file, a terminfo entry source or …'
complete -c 'toe.1m' -s v -d 'R n ] reports verbose status information to the standard error stream, showin…'
complete -c 'toe.1m' -s a -d 'lists entries from all terminal database directories that terminfo would sear…'
complete -c 'toe.1m' -s V -d 'reports the version of %ncurses associated with this program and exits with a…'

