# tput
# Autogenerated from man page /usr/share/man/man1/tput.1.gz
complete -c tput -s T -d '-S retrieves more than one capability per invocation of \\%tput'
complete -c tput -s V -d 'reports the version of  \\%ncurses associated with \\%tput, and exits with a su…'
complete -c tput -s S -d 'retrieves more than one capability per invocation of %tput'
complete -c tput -s x -d 'prevents %“from attempting to clear the scrollback buffer'

