# tracker3-search
# Autogenerated from man page /usr/share/man/man1/tracker3-search.1.gz
complete -c tracker3-search -s l -l limit -d 'Limit search to limit results'
complete -c tracker3-search -s o -l offset -d 'Offset the search results by offset'
complete -c tracker3-search -s r -l or-operator -d 'Use OR for search terms instead of AND (the default)'
complete -c tracker3-search -s d -l detailed -d 'Show the unique URN associated with each search result'
complete -c tracker3-search -s a -l all -d 'Show results which might not be available'
complete -c tracker3-search -l disable-snippets -d 'Results are shown with snippets'
complete -c tracker3-search -l disable-fts -d 'If Full Text Search (FTS) is available, this option allows it to be disabled …'
complete -c tracker3-search -l disable-color -d 'This disables any ANSI color use on the command line'
complete -c tracker3-search -l folders -d 'for example), then ALL items in that category are returned'
complete -c tracker3-search -s f -l files
complete -c tracker3-search -s s
complete -c tracker3-search -s m -l music
complete -c tracker3-search -l music-albums
complete -c tracker3-search -l music-artists
complete -c tracker3-search -s i -l images
complete -c tracker3-search -s v -l videos
complete -c tracker3-search -s t -l documents
complete -c tracker3-search -l software
complete -c tracker3-search -l software-categories
complete -c tracker3-search -l feeds

