# traptoemail
# Autogenerated from man page /usr/share/man/man1/traptoemail.1.gz
complete -c traptoemail -s f -d 'sender address, defaults to "root"'
complete -c traptoemail -s s -d 'SMTP server, defaults to "localhost"'

