# unixcmd
# Autogenerated from man page /usr/share/man/man1/unixcmd.1.gz
complete -c unixcmd -s s -d 'management socket path (default is /var/run/unixcmd)'
complete -c unixcmd -s f -d 'configuration path (default is /etc/unixcmd)'
complete -c unixcmd -s v -d 'run parse machine in debug mode'

