# varlinkctl
# Autogenerated from man page /usr/share/man/man1/varlinkctl.1.gz
complete -c varlinkctl -l more -d 'When used with call: expect multiple method replies'
complete -c varlinkctl -l collect -d 'This is similar to --more but collects all responses in a JSON array, and pri…'
complete -c varlinkctl -l oneway -d 'When used with call: do not expect a method reply'
complete -c varlinkctl -l json -d 'Selects the JSON output formatting, one of "pretty" (for nicely indented, col…'
complete -c varlinkctl -s j -d 'Equivalent to --json=pretty when invoked interactively from a terminal'
complete -c varlinkctl -l no-pager -d 'Do not pipe output into a pager'
complete -c varlinkctl -s h -l help -d 'Print a short help text and exit'
complete -c varlinkctl -l version -d 'Print a short version string and exit'

