# vde_vxlan
# Autogenerated from man page /usr/share/man/man1/vde_vxlan.1.gz
complete -c vde_vxlan -l vxlan-id -d 'ID of the VXLAN (VNI)'
complete -c vde_vxlan -l vxlan-addr -d 'Multicast address of the VXLAN'
complete -c vde_vxlan -l vxlan-port -d 'Port of the VXLAN (default 4879)'
complete -c vde_vxlan -l vxlan-mttl -d 'Multicast TTL (default 1)'
complete -c vde_vxlan -l sock -d 'Socket directory of the VDE switch'
complete -c vde_vxlan -l port -d 'Port of the VDE switch'
complete -c vde_vxlan -l daemon -d 'Run in background'
complete -c vde_vxlan -l verbose -d 'Show debug output'

