# vde_pcapplug
# Autogenerated from man page /usr/share/man/man1/vde_pcapplug.1.gz
complete -c vde_pcapplug -s p -l port -d 'It is possible to decide which port of the switch to use'
complete -c vde_pcapplug -s g -l group -d 'group ownership of the communication socket'
complete -c vde_pcapplug -s m -l mod -d 'octal chmod like permissions for the comm sockets'
complete -c vde_pcapplug -s s -l sock -d 'specify the UNIX socket to be used by local programs for joining the VDE'
complete -c vde_pcapplug -s d -l daemon -d 'start vde_plug2tap as a background process'
complete -c vde_pcapplug -s P -l pidfile -d 'put the process ID of vde_plug2tap in pidfile'
complete -c vde_pcapplug -s h -l help -d 'show a brief help'

