# vde_autolink
# Autogenerated from man page /usr/share/man/man1/vde_autolink.1.gz
complete -c vde_autolink -s h -l help -d 'Display this help'
complete -c vde_autolink -s f -l rcfile -d 'Configuration file (overrides /etc/vde_autolink. rc and ~/. vde_autolinkrc)'
complete -c vde_autolink -s d -l daemon -d 'Daemonize vde_autolink once run'
complete -c vde_autolink -s p -l pidfile -d 'Write pid of daemon to PIDFILE'
complete -c vde_autolink -s M -l mgmt -d 'Path of the management UNIX socket'
complete -c vde_autolink -l mgmtmode -d 'Management UNIX socket access mode (octal)'
complete -c vde_autolink -s s -l sock -d '[*] Attach to this vde_switch socket'
complete -c vde_autolink -s S -l switchmgmt -d '[*] Attach to this vde_switch management socket P [*] == Required option! -h,…'

