# vde_switch
# Autogenerated from man page /usr/share/man/man1/vde_switch.1.gz
complete -c vde_switch -o hub -d 'turn off the switch engine.  It operates as a hub'
complete -c vde_switch -o sock -d 'specify the directory when comm socket are created'
complete -c vde_switch -o mod -d 'specify the octal permissions for the comm sockets'
complete -c vde_switch -o group -d 'specify the group owner for the comm socket'
complete -c vde_switch -o tap -d 'connect the specified tuntap interface to this vde_switch (needs root privile…'
complete -c vde_switch -o daemon -d 'Run as a daemon.  Use syslog for logging'
complete -c vde_switch -s f -d 'rc file to set the initial switch configuration'
complete -c vde_switch -o nostdin -d 'Allow stdin to be closed'
complete -c vde_switch -s h -d 'help.  Please use it for a more complete list of options'

