# vde_router
# Autogenerated from man page /usr/share/man/man1/vde_router.1.gz
complete -c vde_router -s d -d 'Daemonize the process and put in background'
complete -c vde_router -s r -d 'Parse configuration parameters from configfile at startup'
complete -c vde_router -s M -d 'the unix socket where the parameters (interfaces addresses, routes, etc'
complete -c vde_router -s m -d 'Specify the permission for the access to mgmt_socket'
complete -c vde_router -s p -d 'Save the process id to pidfile NOTICE Virtual Distributed Ethernet is not rel…'

