# vde_cryptcab
# Autogenerated from man page /usr/share/man/man1/vde_cryptcab.1.gz
complete -c vde_cryptcab -s p -d 'It is possible to decide which local udp port to use'
complete -c vde_cryptcab -s c -d 'run vde_cryptcab in client mode, trying to connect to   host '
complete -c vde_cryptcab -s s -d 'specify the UNIX socket to be used by local programs for joining the VDE'
complete -c vde_cryptcab -s P -d 'if specified, vde_cryptcab will run in pre-shared key mode, instead of genera…'
complete -c vde_cryptcab -s x -d 'Disable symmetric key encryption'
complete -c vde_cryptcab -s k -d 'Send periodic "keepalive" packets to avoid server timeouts'
complete -c vde_cryptcab -s d -d 'Run as daemon'
complete -c vde_cryptcab -s v -d Verbose

