# vde_over_ns
# Autogenerated from man page /usr/share/man/man1/vde_over_ns.1.gz
complete -c vde_over_ns -s s -d 'If specified, the vde_over_ns will connect to the local vde socket vdeplug in…'
complete -c vde_over_ns -s D -d 'Detach console and send the process to background'
complete -c vde_over_ns -s b -d 'The NS server will bind only to the specified ip, instead of any ip'
complete -c vde_over_ns -s c -d 'If specified, client mode is enabled'

