# vde_plug
# Autogenerated from man page /usr/share/man/man1/vde_plug.1.gz
complete -c vde_plug -s p -d 'It is possible to decide which port of the switch to use'
complete -c vde_plug -s g -d 'group ownership of the communication socket'
complete -c vde_plug -s m -d 'octal chmod like permissions for the comm sockets'
complete -c vde_plug -o sock -d ') specify the directory which contains the UNIX socket to be used by local pr…'

