# vdecmd
# Autogenerated from man page /usr/share/man/man1/vdecmd.1.gz
complete -c vdecmd -s s -d 'management socket path (default is /var/run/unixcmd)'
complete -c vdecmd -s f -d 'configuration path (default is /etc/unixcmd)'
complete -c vdecmd -s v -d 'run parse machine in debug mode'

