# vdeq
# Autogenerated from man page /usr/share/man/man1/vdeq.1.gz
complete -c vdeq -l mod -d 'octalmode,  specify the mode for comm socket. br'
complete -c vdeq -o sock -d 'socketpath,  specify the UNIX socket to be used by local programs for joining…'
complete -c vdeq -s h -o help -l help -d 'print a Usage help.  NOTE Qemu has changed its syntax for networking (cvs Nov'

