# winpr-makecert3
# Autogenerated from man page /usr/share/man/man1/winpr-makecert3.1.gz
complete -c winpr-makecert3 -o rdp -d 'Dummy parameter'
complete -c winpr-makecert3 -o silent -d 'Don\'t print the generated certificate to stdout'
complete -c winpr-makecert3 -s f -d 'Three formats are supported: crt, pem and pfx'
complete -c winpr-makecert3 -s p -d 'Password to use if the pfx format is used as format'
complete -c winpr-makecert3 -o live -d 'Don\'t write the key/certificate to disk'
complete -c winpr-makecert3 -s n -d 'The common name to use in the certificate'
complete -c winpr-makecert3 -s m -d 'Validity period in months (multiple of 31 days, not clanendar months)'
complete -c winpr-makecert3 -s y -d 'Validity period in years (365 days, leap years not accounted)'
complete -c winpr-makecert3 -o len -d 'Key length in bits to use'
complete -c winpr-makecert3 -s a -d 'The hashing algorithm to use'
complete -c winpr-makecert3 -s '#' -d 'The serial number to use for the certificate'
complete -c winpr-makecert3 -o path -d 'A directory where the certificate should be created in'

