# wvtag
# Autogenerated from man page /usr/share/man/man1/wvtag.1.gz
complete -c wvtag -l allow-huge-tags -d 'allow tag data up to 16 MB'
complete -c wvtag -s c -d 'extract cuesheet only to stdout (equivalent to x cuesheet )'
complete -c wvtag -o cc -d 'extract cuesheet to source-name'
complete -c wvtag -l clean -d 'clean all items from tag (done first)'
complete -c wvtag -s d -d 'delete specified metadata item (text or binary)'
complete -c wvtag -s h -d 'display this help'
complete -c wvtag -l import-id3 -d 'import applicable tag items from ID3v2'
complete -c wvtag -s l -d 'list all tag items (done last)'
complete -c wvtag -l no-utf8-convert -d 'don\'t recode passed tags from local encoding to UTF-8, assume they are in UTF…'
complete -c wvtag -s q -d 'Be quiet: keep console output to a minimum'
complete -c wvtag -s v -d 'Write program version to stdout'
complete -c wvtag -s w -d 'delete specified metadata item (text or binary)'
complete -c wvtag -l write-binary-tag -d 'write the specified binary metadata file to APEv2 tag, normally used for cove…'
complete -c wvtag -s x -d 'extract the specified tag field only to stdout'
complete -c wvtag -o xx -d 'extract the specified tag field into a named file in same directory as source…'
complete -c wvtag -s y -d 'yes to all warnings; use with caution! El SEE ALSO wavpack 1, wvgain 1, wvunp…'

