# xfreerdp3
# Autogenerated from man page /usr/share/man/man1/xfreerdp3.1.gz
complete -c xfreerdp3 -o authentication -d 'Authentication (experimental) (default:on)'
complete -c xfreerdp3 -o compression -s z -d 'compression (default:on)'
complete -c xfreerdp3 -o decorations -d 'Window decorations (default:on)'
complete -c xfreerdp3 -o encryption -d 'Encryption (experimental) (default:on)'
complete -c xfreerdp3 -o fonts -d 'smooth fonts (ClearType) (default:on)'
complete -c xfreerdp3 -o grab-keyboard -d 'Grab keyboard (default:on)'
complete -c xfreerdp3 -o grab-mouse -d 'Grab mouse (default:on)'
complete -c xfreerdp3 -o heartbeat -d 'Support heartbeat PDUs (default:on)'
complete -c xfreerdp3 -o mouse-motion -d 'Send mouse motion (default:on)'
complete -c xfreerdp3 -o multitransport -d 'Support multitransport protocol (default:on)'
complete -c xfreerdp3 -o nego -d 'protocol security negotiation (default:on)'
complete -c xfreerdp3 -o suppress-output -d 'suppress output when minimized (default:on)'
complete -c xfreerdp3 -o themes -d 'themes (default:on)'
complete -c xfreerdp3 -o toggle-fullscreen -d 'Alt+Ctrl+Enter to toggle fullscreen (default:on)'
complete -c xfreerdp3 -o wallpaper -d 'wallpaper (default:on)'

